# Generated by Django 3.0.5 on 2022-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignment',
            name='keyword',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
