# Generated by Django 3.0.5 on 2022-02-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classassignment_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='assignment',
            field=models.ImageField(upload_to='assignments'),
        ),
    ]
